version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  deploy-staging:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: sh ./scripts/setup_dotenv.sh
      - run: sh ./scripts/deploy_lambda.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-staging:
          context: notion-api-integration
          filters:
            branches:
              only: master
